-- ============================================================
-- Migration 008: Brand Visibility & Analytics Intelligence
-- ============================================================

-- Brand visibility reports (search landscape snapshots)
CREATE TABLE IF NOT EXISTS brand_visibility_reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  brand_name TEXT NOT NULL,
  domain TEXT NOT NULL,
  target_keywords TEXT[] NOT NULL,
  competitor_domains TEXT[] DEFAULT '{}',

  -- Scores (0-100)
  overall_score INTEGER,
  organic_score INTEGER,
  ai_overview_score INTEGER,
  llm_score INTEGER,
  paid_score INTEGER,

  -- Detailed results (JSONB)
  organic_results JSONB DEFAULT '{}',
  ai_overview_results JSONB DEFAULT '{}',
  llm_results JSONB DEFAULT '{}',
  paid_results JSONB DEFAULT '{}',
  competitor_comparison JSONB DEFAULT '{}',
  recommendations JSONB DEFAULT '[]',

  -- Metadata
  api_cost_cents INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_bvr_domain ON brand_visibility_reports(domain, created_at DESC);

-- Analytics snapshots (GA4 data, stored for trend analysis)
CREATE TABLE IF NOT EXISTS analytics_snapshots (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,

  -- GA4 data sections
  traffic JSONB DEFAULT '{}',         -- sessions, users, pageviews, bounce_rate
  landing_pages JSONB DEFAULT '[]',   -- per-page metrics
  acquisition JSONB DEFAULT '{}',     -- source/medium breakdown
  conversions JSONB DEFAULT '{}',     -- key events, rates
  ad_traffic JSONB DEFAULT '{}',      -- post-click behavior for ads
  device_split JSONB DEFAULT '{}',    -- mobile vs desktop

  -- Analysis results (generated by deterministic code, not LLM)
  flags JSONB DEFAULT '[]',           -- detected issues with thresholds
  recommendations JSONB DEFAULT '[]', -- selected from catalog
  scores JSONB DEFAULT '{}',          -- computed scores

  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(period_start, period_end)
);

CREATE INDEX IF NOT EXISTS idx_analytics_period ON analytics_snapshots(period_start DESC);

-- Add GA4 property ID to Google Ads accounts
ALTER TABLE google_ads_accounts ADD COLUMN IF NOT EXISTS ga4_property_id TEXT;
